### ISSUE TITLE
background-size and background-position on IE9 with 'vw'

### ISSUE THREAD

**Issue by mdeweerd** [louisremi/background-size-polyfill#45]
Hi
In order to get the same view in IE9, I have to device background-size and background-position differently.
Maybe something that you may want to consider for your behavior...

Test in IE9 and other browsers with the fiddle:
http://jsfiddle.net/fBhXf/10/

Basically this example is for a 

```
<div id='example'></div>
```

 and with CSS:

```
#example {
    background-image:url(http://www.ipreferjim.com/site/wp-content/uploads/2012/10/markers.png);
    background-size:100vw;
    background-position:-20vw -20vw;
    width:10vw;
    height:10vw;
    border:solid green 1em;
}
.lt-ie10 #example {
    background-size:1000vw;
    background-position:22vw 22vw;
    width:0.2vw;
    height:0.2vw;
}
```

Where '.lt-le10' identifies the browser as before IE 10.

**Comment by jefferyto** [comment]
Thanks for raising this. There seems to be several issues with `vw`/`vh` units in IE9 (in an iframe, `1vw` is 100% of the viewport width; when applied to background properties, `vw` is relative to the element's width rather than the viewport). Without a clear idea of what needs to be fixed (I've only done some cursory tests based on your example) it would be hard to address this.

Also, the polyfill is only meant for IE7/8, which lacks any support for these units. I'd say that if you're supporting IE7/8 then the safest course would be to stay away from using these units altogether.

**Comment by mdeweerd** [comment]
Very old ticket - no longer expecting this to be implemented.
